name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io/jonohill
  DOCKER_REPO: terraform-vaultwarden

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (Pre) build image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.actor != 'renovate[bot]' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ github.run_number }}-dev"

      - name: Get vaultwarden version
        id: vaultwarden_version
        if: ${{ github.actor != 'renovate[bot]' }}
        run: |
          version=$(docker run --entrypoint /vaultwarden "${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_REPO }}:${{ github.run_number }}-dev" --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> $GITHUB_OUTPUT          

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v6
        if: ${{ github.actor != 'renovate[bot]' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: |
            "${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_REPO }}:latest"
            "${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_REPO }}:${{ steps.vaultwarden_version.outputs.version }}"
